### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte ...

### ISSUE THREAD

**Issue by companje** [hetutrechtsarchief/MFXML-to-JSONLD#2]
bob: Als ik BEELDBANK_14_131_flexis-50000.txt erdoor heen haal dan zie ik in de log de volgende fout:

```
Traceback (most recent call last): File "mf2jsonld.py", line 280, in <module> for line in file: File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode return codecs.ascii_decode(input, self.errors)[0] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2929: ordinal not in range(128) 
```

**Comment by companje** [comment]
test-bestand: [1record.txt](https://github.com/hetutrechtsarchief/MFXML-to-JSONLD/files/5450577/1record.txt)

**Comment by companje** [comment]
bob: Als ik de "ensure_ascii=False" weghaal dan verdwijnt ook die ascii error.
